### ISSUE TITLE
Pressing `*` in the demo page does nothing. The other listed keys work fine.

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-a11y-keys#10]
on a German keyboard

**Comment by JacekKosciesza** [comment]
Does not work for me (shift 8 and number pad), too. I'm using Polish (Programmers) Keyboard. I've also tried using other keys e.g. 'a' and 'escape' by modifying keys attribute on demo page like this:
`<iron-a11y-keys id="keys" keys="escape a * pageup pagedown left right down up shift+a alt+a home end space enter" class="style-scope x-key-aware"></iron-a11y-keys>`
and 'a' works ok, but 'escape' does not.

**Comment by miztroh-zz** [comment]
My suspicion here is that `*` is a wildcard.  The `keys` would need to include `shift+8` to intercept the combination you're talking about.

**Comment by cdata** [comment]
This issue appears to be fixed in master. Please re-open the issue if you think there is still a problem!
