### ISSUE TITLE
Docs: Add 'meta' as one of the potential modifier keys

### ISSUE THREAD

**Issue by miztroh-zz** [PolymerElements/iron-a11y-keys#21]

**Comment by notwaldorf** [comment]
I think you're looking for `meta`: http://jsbin.com/lohesa/edit?html,output

**Comment by miztroh-zz** [comment]
@notwaldorf That's how I normally refer to it as well, but I couldn't find any mention of meta in the docs: https://elements.polymer-project.org/elements/iron-a11y-keys

**Comment by miztroh-zz** [comment]
@notwaldorf In fact, the docs explicitly say "The modifier keys are: Shift, Control, Alt."

**Comment by notwaldorf** [comment]
Ah yes, that sounds like a documentation bug. Re-opening and re-titling :)

Would you be interested in sending a patch to fix that?

**Comment by miztroh-zz** [comment]
@notwaldorf No problem: https://github.com/PolymerElements/iron-a11y-keys/pull/22

**Comment by jarrodek** [comment]
The docs are still showing docs without the PR even if the PR was already merged with master.
