### ISSUE TITLE
Binding to specific events (documentation)

### ISSUE THREAD

**Issue by robrez** [PolymerElements/iron-a11y-keys#28]
In `iron-a11y-keys-behavior` there is some documentation demonstrating how to bind to specific key\* events..

```
 keyBindings: {
   'space': '_onKeydown', // same as 'space:keydown'
   'shift+tab': '_onKeydown',
   'enter:keypress': '_onKeypress',
   'esc:keyup': '_onKeyup'
 }
```

For me, it took a bit of reading the code to determine that the same syntax can be used in the `keys` attr..

```
  <iron-a11y-keys
      keys="space shift+tab enter:keypress esc:keyup"
      on-keys-pressed="_myHandler">
  </iron-a11y-keys>
```

Is there any opposition to adding an example like the above to docs for `iron-a11y-keys`?

**Comment by valdrinkoshi** [comment]
@robrez I would add the [`keys` property jsdoc](https://github.com/PolymerElements/iron-a11y-keys/blob/master/iron-a11y-keys.html#L146) describing what's the format and expand [the "Example" section](https://github.com/PolymerElements/iron-a11y-keys/blob/master/iron-a11y-keys.html#L93) of the "`keys` attribute" paragraph with something like:

> Each key supports the following format: `KEY[+MODIFIER][:TRIGGERING_EVENT]`
> e.g. `keys = "space shift+tab enter:keyup alt+ctrl+canc:keypress"`

WDYT? Feel free to open a PR if you fee like it :)

**Comment by robrez** [comment]
That's a good idea. Will try to submit a pr this weekend

**Comment by robrez** [comment]
Ooos! Accidentally clicked close instead of comment
