### ISSUE TITLE
stopKeyboardEventPropagation doesn't stop propagation 

### ISSUE THREAD

**Issue by ryanwtyler** [PolymerElements/iron-a11y-keys#35]
when i have 
`<iron-a11y-keys
      id="keys"
      keys="meta+s"
      target="[[target]]"
      on-keys-pressed="_updatePressed"
      stopKeyboardEventPropagation>
    </iron-a11y-keys>`

and click cmd-s the event handler _updatePressed is called but the event gets to window and the browser save is executed.  i can prevent the event from bubbling by calling `e.detail.keyboardEvent.preventDefault();` in the event handler

### Expected outcome

event is captured and propagation is stopped

### Actual outcome

browser save is run

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
properties must be set in the markup with hyphens instead of camel case, e.g.
`<iron-a11y-keys id="keys" keys="meta+s" target="[[target]]" on-keys-pressed="_updatePressed" stop-keyboard-event-propagation> </iron-a11y-keys>`
